export default {
    access: 'Acceder',
    addDescription: 'Agrega una descripción',
    addMessage: 'Escribe un mensaje',
    confirmPassword: 'Confirmar contraseña',
    description: 'Descripción',
    ingressDescription: 'Ingresa una descripción',
    ingressEmail: 'Ingresa tu correo electrónico',
    ingressName: 'Ingresa tu nombre',
    ingressPassword: 'Ingresar contraseña',
    editProfile: 'Editar perfil',
    email: 'Correo electrónico',
    emailAlreadyUsed: 'El email ya está registrado',
    error: 'Error.',
    favorites: 'Favoritos',
    flightsNumber: 'Número de vuelos',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    name: 'Nombre',
    password: 'Contraseña',
    register: 'Registro',
    saveChanges: 'Guardar cambios',
    termsAndConditions: 'Acepto los términos y condiciones',
    wrongPassword: 'Email o contraseña incorrectos'
}